### ISSUE TITLE
Implementation uses deprecated classes

### ISSUE THREAD

**Issue by marcoschleiwies** [chriskn/structurizr-c4puml-extension#58]
Hi Christoph,

I have read all your excellent articles on the codecentric blog and its fits actually perfect in my work. So I wanted to try out your implemented "ExtendedC4PlantUmlWriter" as I have also found the exported diagrams via format "plantuml/c4plantuml" - even with linetpe "ortho" or "multiline" -do not look "perfect".

To use your implementation I have found out that it seems that your implementation uses the deprecated java-extension-package instead of the exporter-package.  Could you please refactor your implementation ?

As it is now I cannot use your implementation. I am using DSL with CLI and would like to use your implementation to format the output during the export with "--format com.structurizr.io.plantuml.ExtendedC4PlantUmlWriter".
Or then after your fix "--format com.structurizr.export.plantuml.ExtendedC4PlantUmlExporter" ?

Using Java or Kotlin are actually no options. I am kind of bound to the DSL in the moment.

Kind regards,
Marco

**Comment by chriskn** [comment]
Hi @marcoschleiwies, 

thank you for your feedback. Refactoring the exporter to use the new exporter API is on my to-do list. Since the refactoring is a bigger task, I am not sure when I find the time, but I will do my test to make it in the next weeks. 

I am not using the DSL or the web workspace. This extension is not tested with Structurizr models created via the DSL. So I don't know how good your approach will work even after I refactored the exporter.

**Comment by marcoschleiwies** [comment]
That sounds good.

And as you said - the test concerning the usage of your implementation is of course my part. And I even do not know what the result/test will bring up. But I have an idea and will try to check if that will work.

**Comment by chriskn** [comment]
I switched to the exporter API with this commit 6dd4ef4
